ALTER TABLE users ADD COLUMN wins INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN losses INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN streak INT NOT NULL DEFAULT 0; -- +2 for W2, -1 for L1
ALTER TABLE users ADD COLUMN trend VARCHAR(20) NOT NULL DEFAULT 'STAGNANT'; -- 'UP', 'DOWN', 'STAGNANT'
